[project]
name = "gpt-oss-reverse-engineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipykernel>=6.30.1",
    "requests>=2.32.4",
    "tqdm>=4.67.1",
]
